CREATE USER C##carrito IDENTIFIED BY carrito123
DEFAULT TABLESPACE USERS
TEMPORARY TABLESPACE TEMP;

GRANT DBA TO C##carrito;
GRANT ALL PRIVILEGES TO C##carrito;
GRANT UNLIMITED TABLESPACE TO C##carrito;
